### ISSUE TITLE
UpdClient#SendAsync cannot be multithreaded; Making the threads parameter useless

### ISSUE THREAD

**Issue by AlmightyLks** [LUCKYONE-CC/Shredder#3]
The following lines and code paths are affected: 
https://github.com/LUCKYONE-CC/Shredder/blob/72579f8f85e2688fb82e5087179ccb6ba25f0ff5/Program.cs#L53
https://github.com/LUCKYONE-CC/Shredder/blob/72579f8f85e2688fb82e5087179ccb6ba25f0ff5/Program.cs#L67
https://github.com/LUCKYONE-CC/Shredder/blob/72579f8f85e2688fb82e5087179ccb6ba25f0ff5/Shred.cs#L39-L42

---

When replacing the "100" with only "1" you will notice that both 100 threads and 1 thread yield the same throughput.  

![image](https://github.com/LUCKYONE-CC/Shredder/assets/54688434/7ac3f717-9b2c-4e0d-a5e5-b4abaf5187b2)  

![image](https://github.com/LUCKYONE-CC/Shredder/assets/54688434/7beeb900-f798-4a10-8a48-6c991853dd12)

---

That's because Sockets do not allow concurrent SendAsync() calls. 

See
https://github.com/dotnet/runtime/issues/26843#issuecomment-406227495
https://tangentsoft.com/wskfaq/intermediate.html#threadsafety

> 3.10 - Is Winsock thread-safe?
> On [modern](https://tangentsoft.com/wskfaq/intro.html#versions) Windows stacks, yes, it is, within limits.
> It is safe, for instance, to have one thread calling send() and another thread calling recv() on a single socket.
> By contrast, it’s a bad idea for two threads to both be calling send() on a single socket. This is “thread-safe” in the limited sense that your program shouldn’t crash, and you certainly shouldn’t be able to crash the kernel, which is handling these send() calls. The fact that it is “safe” doesn’t answer key questions about the actual effect of doing this. Which call’s data goes out first on the connection? Does it get interleaved somehow? Don’t do this.
> Instead of multiple threads accessing asingle socket, you may want to consider setting up a pair of network I/O queues.

**Comment by LUCKYONE-CC** [comment]
Thank you for your feedback!
The latest version now no longer uses multithreading at this point.
