### ISSUE TITLE
Calling Shred#Info twice

### ISSUE THREAD

**Issue by AlmightyLks** [LUCKYONE-CC/Shredder#4]
https://github.com/LUCKYONE-CC/Shredder/blob/4dc09b17bb9baa67871be173fa56298b4af3115d/Shred.cs#L39
https://github.com/LUCKYONE-CC/Shredder/blob/4dc09b17bb9baa67871be173fa56298b4af3115d/Program.cs#L58

See title. I dont think it should do that?

**Comment by LUCKYONE-CC** [comment]
Fixed
